// **Every county and realm field `Lords2.exe` reads or writes** — the original's
// side of `docs/stored-fields.json`.
//
//   node tools/oracle/fields.js              # the table: record, offset, name, who writes, who reads
//   node tools/oracle/fields.js --uncovered  # only the offsets no inventory row covers
//   node tools/oracle/fields.js --check      # fail if any accessed offset has no row
//
// **Why this exists.** Three times in one week a number a player could see was
// stored by the original, carried by our save format, drawn by our painter — and
// never read by `l2-scenario`, so a loaded game showed zero until a season ended
// (`docs/decisions.md` C142, C153, C161). The
// exhaustive destructure of `CountyState` could not catch any of them, because a
// field never added to `CountyState` is not in the list that destructure
// enumerates. The denominator has to come from the original, not from us.
//
// `docs/records.json` is not that denominator either: it lists the fields someone
// has *named*, and its `Industry` base was four bytes wrong the week this was
// written. So this reads the decompilation — every `g_counties[i].x`,
// `g_counties[i].field_0xNNN`, `i * 0x300 + 0x53fXXX` and absolute `DAT_` inside
// the array, and the same four shapes for `g_realms` — and reports each offset
// with the functions that touch it. `crates/l2-scenario/tests/stored_fields.rs`
// is the tree's side and runs everywhere; this needs the corpus and runs here.
//
// Reads `tools/oracle/decomp/*.c`, which is gitignored — regenerate it with
// `tools/oracle/decompile-all.ps1`. A site is attributed to the function whose
// `// ==== <addr> <name>` header it falls under.
//
// **What it cannot see**, said beside the number: an access through a pointer
// the decompiler did not type (`piVar3 = &g_counties[i].labour; piVar3[2]`) is
// attributed to the field the pointer was taken from, not to the element; and a
// county record handed to a callee as a bare `int` is invisible. Both are why
// `--check` is a lower bound on the stored set, never an upper one.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
// `LORDS2_DECOMP` overrides it — a git worktree has no copy of the gitignored
// corpus, and the main checkout's is the same bytes.
const DECOMP = process.env.LORDS2_DECOMP || path.join(__dirname, 'decomp');
const RECORDS = path.join(ROOT, 'docs', 'records.json');
const INVENTORY = path.join(ROOT, 'docs', 'stored-fields.json');

const WIDTH = { u8: 1, i8: 1, u16: 2, i16: 2, u32: 4, i32: 4 };

/// The two arrays this inventory is about: base address, stride, record count.
const ARRAYS = {
  County: { base: 0x0053f9b0, stride: 0x300, count: 17, global: 'g_counties' },
  Realm: { base: 0x0057bf00, stride: 0x160, count: 6, global: 'g_realms' },
};

function loadStructs() {
  const j = JSON.parse(fs.readFileSync(RECORDS, 'utf8'));
  const byName = {};
  for (const s of j.structs) byName[s.name] = s;
  return byName;
}

/// `"i32[8]"` -> `{ elem: "i32", count: 8 }`; `"u8"` -> count 1.
function parseType(t) {
  const m = t.match(/^([A-Za-z0-9]+)(?:\[(\d+)\])?$/);
  return { elem: m[1], count: m[2] ? Number(m[2]) : 1 };
}

/// The struct's fields as rows: scalars, scalar arrays, and — for an array of a
/// nested struct — one row per sub-field with a stride. Offsets are relative to
/// the record.
function flatten(structs, name) {
  const rows = [];
  for (const f of structs[name].fields) {
    const off = parseInt(f.off, 16);
    const { elem, count } = parseType(f.type);
    if (WIDTH[elem]) {
      rows.push({ off, width: WIDTH[elem], count, stride: WIDTH[elem], name: f.name });
    } else if (structs[elem]) {
      for (const sub of structs[elem].fields) {
        const st = parseType(sub.type);
        rows.push({
          off: off + parseInt(sub.off, 16),
          width: WIDTH[st.elem] || 1,
          count,
          stride: structs[elem].size,
          subCount: st.count,
          name: `${f.name}[].${sub.name}`,
        });
      }
    }
  }
  return rows;
}

/// The row of `rows` an offset falls inside, if any.
function rowAt(rows, off) {
  for (const r of rows) {
    const span = (r.count - 1) * r.stride + r.width * (r.subCount || 1);
    if (off < r.off || off >= r.off + span) continue;
    const rel = (off - r.off) % r.stride;
    if (rel < r.width * (r.subCount || 1)) return r;
  }
  return null;
}

/// Member name -> record-relative offset, for the names `ApplyRecords` gave.
function memberOffsets(structs, name) {
  const map = {};
  for (const f of structs[name].fields) map[f.name] = { off: parseInt(f.off, 16), type: f.type };
  // Names the corpus was decompiled under and `docs/records.json` has since
  // renamed. The corpus is only regenerated by `decompile-all.ps1`, so a rename
  // strands its old spelling here until somebody reruns it.
  for (const [old, now] of Object.entries(RENAMED[name] || {})) {
    if (map[now] && !map[old]) map[old] = map[now];
  }
  return map;
}

/// `old name -> current name`, per record. `herdChangeFromFarming` became
/// `herdOverallChange` in docs/decisions.md C128.
const RENAMED = { County: { herdChangeFromFarming: 'herdOverallChange' } };

function scan(structs) {
  if (!fs.existsSync(DECOMP)) {
    console.error(`no corpus at ${DECOMP} - run tools/oracle/decompile-all.ps1`);
    process.exit(2);
  }
  // record -> offset -> { writers: Set, readers: Set }
  const hits = { County: new Map(), Realm: new Map() };
  const note = (rec, off, fn, write) => {
    const m = hits[rec];
    if (!m.has(off)) m.set(off, { writers: new Set(), readers: new Set() });
    (write ? m.get(off).writers : m.get(off).readers).add(fn);
  };
  const isWrite = (rest) => /^\s*(=(?!=)|\+\+|--|[-+*\/|&^]=|<<=|>>=)/.test(rest);

  const members = { County: memberOffsets(structs, 'County'), Realm: memberOffsets(structs, 'Realm') };
  const files = fs.readdirSync(DECOMP).filter((n) => n.endsWith('.c')).sort();
  const texts = files.map((f) => fs.readFileSync(path.join(DECOMP, f), 'utf8'));

  // **Which Industry layout the corpus was decompiled under.** The corpus is the
  // output of `ApplyRecords.java` at the moment it last ran, not of
  // `docs/records.json` today, and C153 moved the array's base from
  // +0x290 to +0x294 without re-running it. Under the old layout every sub-field
  // sat four bytes higher in a record four bytes lower — the same absolute
  // offsets for every NAMED field — but the array's own base, and any unnamed
  // `field_0xN` inside it, resolve four bytes apart. The county's `weaponType`
  // byte is read as `*(byte *)g_counties[x].industry`, and resolving that
  // against today's base put it on `efficiency` and left +0x290 "untouched".
  // Only the new layout names `nextSeason`, so its absence says which one this is.
  const staleIndustry = !texts.some((t) => /\.industry\[[^\]]*\]\.nextSeason/.test(t));
  const CORPUS_SHIFT = staleIndustry ? { industry: 4 } : {};
  if (staleIndustry) {
    console.error(
      'corpus: decompiled under the pre-C153 Industry layout (base +0x290); resolving accordingly',
    );
  }
  const nestedSize = (type) => {
    const { elem } = parseType(type);
    return structs[elem] ? structs[elem] : null;
  };

  for (const [fi, f] of files.entries()) {
    const lines = texts[fi].split(/\r?\n/);
    let fn = '?';
    for (const line of lines) {
      const h = line.match(/^\/\/ ==== ([0-9a-f]{8})\s+(\S+)/);
      if (h) {
        fn = `${h[2]}@0x${h[1].toUpperCase()}`;
        continue;
      }
      for (const [rec, a] of Object.entries(ARRAYS)) {
        // 1. g_counties[i].member[j].sub  /  .field_0xNNN  /  ._NNN_W_
        const re = new RegExp(
          `${a.global}\\[[^\\]]*\\]\\.(field_0x[0-9a-f]+|_\\d+_\\d+_|[A-Za-z][A-Za-z0-9]*)` +
            `(?:\\[([^\\]]*)\\])?(?:\\.(field_0x[0-9a-f]+|[A-Za-z][A-Za-z0-9]*))?`,
          'g',
        );
        let m;
        while ((m = re.exec(line))) {
          const [all, member, index, sub] = m;
          const rest = line.slice(m.index + all.length);
          let off;
          let sm = member.match(/^field_0x([0-9a-f]+)$/);
          const wide = member.match(/^_(\d+)_(\d+)_$/);
          if (sm) off = parseInt(sm[1], 16);
          else if (wide) off = Number(wide[1]);
          else if (members[rec][member]) {
            const shift = rec === 'County' ? CORPUS_SHIFT[member] || 0 : 0;
            off = members[rec][member].off - shift;
            const nest = nestedSize(members[rec][member].type);
            if (nest) {
              const lit = index && /^\d+$/.test(index.trim()) ? Number(index) : 0;
              off += lit * nest.size;
              if (sub) {
                const s2 = sub.match(/^field_0x([0-9a-f]+)$/);
                // An unnamed sub-field is already in the corpus's own layout; a
                // named one is looked up in today's and shifted back into it.
                off += s2
                  ? parseInt(s2[1], 16)
                  : parseInt((nest.fields.find((x) => x.name === sub) || { off: 'NaN' }).off, 16) + shift;
              }
            } else if (index && /^\d+$/.test(index.trim())) {
              const { elem } = parseType(members[rec][member].type);
              off += Number(index) * (WIDTH[elem] || 1);
            }
          } else {
            // A name from a DIFFERENT struct typed over this array — Ghidra
            // occasionally does it where two arrays are adjacent. Reported, not
            // guessed at.
            note(rec, `?${member}`, fn, isWrite(rest));
            continue;
          }
          if (Number.isNaN(off)) continue;
          note(rec, off, fn, isWrite(rest));
        }
        // 2. EXPR * 0x300 + 0x53fXXX  (optionally + k * stride). The optional
        // `+ industry * 0x18` before the closing parenthesis is how the
        // industry forecast's only writer spells it, and missing it once made
        // that write look like a read.
        const raw = new RegExp(`\\* 0x${a.stride.toString(16)} \\+ 0x([0-9a-f]{6})`, 'g');
        while ((m = raw.exec(line))) {
          const addr = parseInt(m[1], 16);
          if (addr < a.base || addr >= a.base + a.stride * a.count) continue;
          const tail = line.slice(m.index + m[0].length);
          note(rec, (addr - a.base) % a.stride, fn, /^(\s*\+[^)=;]*)?\)*\s*=(?!=)/.test(tail));
        }
        // 3. absolute DAT_ inside the array.
        const dat = /DAT_00([0-9a-f]{6})/g;
        while ((m = dat.exec(line))) {
          const addr = parseInt(m[1], 16);
          if (addr < a.base || addr >= a.base + a.stride * a.count) continue;
          const tail = line.slice(m.index + m[0].length);
          note(rec, (addr - a.base) % a.stride, fn, /^\)*(\[[^\]]*\])?\s*=(?!=)/.test(tail));
        }
      }
    }
  }
  return hits;
}

/// The inventory rows, one JSON object per line — the same line-oriented shape
/// the Rust side scans without a JSON crate.
function loadInventory() {
  if (!fs.existsSync(INVENTORY)) return [];
  const j = JSON.parse(fs.readFileSync(INVENTORY, 'utf8'));
  // A row carries `type`, not a width — `bool` is one byte on disk. Reading a
  // `width` the rows never had made every row cover nothing, and the first
  // `--check` reported all 320 accessed offsets as uncovered.
  const width = { ...WIDTH, bool: 1 };
  return j.fields.map((r) => {
    if (!width[r.type]) throw new Error(`${r.id}: type ${r.type} is not one of ${Object.keys(width)}`);
    return {
      ...r,
      record: r.id.split('+')[0],
      off: parseInt(r.id.split('+')[1], 16),
      width: width[r.type],
    };
  });
}

/// Does an inventory row cover a record-relative offset?
function covers(row, off) {
  const count = row.count || 1;
  const stride = row.stride || row.width;
  if (off < row.off || off >= row.off + (count - 1) * stride + row.width) return false;
  return (off - row.off) % stride < row.width;
}

function main() {
  const structs = loadStructs();
  const hits = scan(structs);
  const inv = loadInventory();
  const layout = { County: flatten(structs, 'County'), Realm: flatten(structs, 'Realm') };
  const hex = (n) => '0x' + n.toString(16).toUpperCase().padStart(3, '0');

  const uncovered = [];
  const table = [];
  for (const rec of Object.keys(ARRAYS)) {
    const offs = [...hits[rec].keys()].sort((x, y) =>
      typeof x === 'number' && typeof y === 'number' ? x - y : String(x).localeCompare(String(y)),
    );
    for (const off of offs) {
      const h = hits[rec].get(off);
      if (typeof off !== 'number') {
        table.push({ rec, off: String(off), name: '(foreign member)', h, row: null });
        continue;
      }
      const lay = rowAt(layout[rec], off);
      const row = inv.find((r) => r.record === rec && covers(r, off));
      table.push({ rec, off: hex(off), name: lay ? lay.name : '', h, row });
      if (!row) uncovered.push({ rec, off: hex(off), name: lay ? lay.name : '', h });
    }
  }

  const fmt = (t) =>
    `${t.rec.padEnd(6)} ${t.off.padEnd(8)} ${(t.name || '-').padEnd(28)} ` +
    `${t.row ? t.row.status.padEnd(9) : 'NO ROW   '} ` +
    `W:${[...t.h.writers].slice(0, 3).join(',') || '-'}  R:${[...t.h.readers].slice(0, 4).join(',') || '-'}`;

  if (process.argv.includes('--check')) {
    const foreign = table.filter((t) => t.name === '(foreign member)');
    const counts = {};
    for (const r of inv) counts[r.status] = (counts[r.status] || 0) + 1;
    console.log(
      `${table.length - foreign.length} accessed offsets (County ${hits.County.size}, Realm ${hits.Realm.size}); ` +
        `${inv.length} inventory rows: ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')}`,
    );
    if (uncovered.length) {
      console.error(
        `\n${uncovered.length} offset(s) Lords2.exe reads or writes that docs/stored-fields.json has no row for:\n` +
          uncovered.map((u) => '  ' + fmt({ ...u, row: null })).join('\n') +
          '\n\nEach is a field the original stores and nothing here has decided about. Add a row: ' +
          '`imported` if l2-scenario carries it, `derived` if the load recomputes it, or `excluded` ' +
          'with a one-line `why`. A field left out of the inventory is how C142 happened.',
      );
      process.exit(1);
    }
    // And the other direction: a row that names an offset the binary never
    // touches is a field we invented.
    const untouched = inv.filter(
      (r) => ![...hits[r.record].keys()].some((o) => typeof o === 'number' && covers(r, o)) && !r.unaccessed,
    );
    if (untouched.length) {
      console.error(
        `\n${untouched.length} row(s) name an offset no decompiled instruction touches:\n` +
          untouched.map((r) => `  ${r.id} ${r.name}`).join('\n') +
          '\n\nEither the offset is wrong, or the access is one this scanner cannot see — say which ' +
          'with `"unaccessed": "<why>"` on the row.',
      );
      process.exit(1);
    }
    console.log('every accessed offset has a row, and every row is accessed');
    return;
  }
  const rows = process.argv.includes('--uncovered') ? uncovered.map((u) => ({ ...u, row: null })) : table;
  for (const t of rows) console.log(fmt(t));
  console.error(`${rows.length} rows`);
}

main();
