#!/usr/bin/env node
// One-shot: merge the battle-simulation names into docs/symbols.json.
// Idempotent - re-running replaces entries with the same address.
//   node tools/battle/addsymbols.js
const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, '..', '..', 'docs', 'symbols.json');

const S = 'battle';
const fn = (addr, name, confidence, signature, comment) =>
  ({ addr, name, section: S, confidence, signature, comment });
const gv = (addr, name, confidence, comment) =>
  ({ addr, name, section: S, confidence, comment });

const functions = [
  fn('0x004778A0', 'Battle_Start', 'verified', 'void Battle_Start(void)',
    'Brings a battle up: builds the battlefield (Battlefield_BuildRandom, Battlefield_BuildFromSkr or Battlefield_BuildCastle), then Battle_InitArmies, then the first unit/figure update passes. See docs/battle.md.'),
  fn('0x0047EFEE', 'Battle_InitArmies', 'verified', 'void Battle_InitArmies(void)',
    'Chooses the battlefield size class from the two armies, clears the figure and unit arrays, then raises both sides. Also computes each side\'s autocalc strength as sum(count[t] * g_troopStrengthWeight[t]) over troop types 0..6.'),
  fn('0x0047FEA7', 'Battle_RaiseSide', 'verified', 'void Battle_RaiseSide(int armyUnit, int outnumbered, int side)',
    'Turns one army record into battle units. Walks the 11 troop types in g_raiseOrder, and for each splits the men into units of at most maxFigures*g_menPerFigure. Siege counts are multiplied by g_menPerFigure so that one engine is one figure. `side` is 4 or 0.'),
  fn('0x004801F8', 'Battle_RaiseSideSiege', 'inferred', 'void Battle_RaiseSideSiege(int armyUnit, int outnumbered, int side)',
    'The castle-defender variant of Battle_RaiseSide: uses g_raiseOrderSiege (8 troop types, no catapult/tower/ram), forces archers and crossbowmen to at most 3 figures per unit, and places units by wall slot rather than by deployment marker.'),
  fn('0x00480599', 'BattleUnit_LoadTroopStats', 'verified', 'void BattleUnit_LoadTroopStats(int troopType)',
    'Copies one row of g_troopBattleStats (0x004D96D0, stride 0x14) into scratch globals, then the matching row of g_missileStats (0x004D97B0) selected by the weapon class in field +0x0C.'),
  fn('0x00480662', 'BattleUnit_Create', 'verified',
    'void BattleUnit_Create(int siegePlacement, int troopType, int outnumbered, int side, int men, int owner, int mercenary)',
    'Allocates a battle unit and fills it with ceil(men / g_menPerFigure) figures laid out in a rectangle. Sets the unit category from the troop type, and copies the troop and missile stats into every figure.'),
  fn('0x0046E4C8', 'BattleMan_Create', 'verified',
    'undefined4 BattleMan_Create(byte troopType, int x0, int dx, int y0, int dy, int owner, short unit)',
    'Allocates the first free slot of the 80-entry figure array g_battleMen (stride 0x1B0), places it on the battlefield, writes its index into cell byte +5 and links it to its unit. Returns 0 when all 80 slots are in use, which silently truncates the army.'),
  fn('0x0046E97A', 'BattleUnit_Alloc', 'verified', 'undefined4 BattleUnit_Alloc(byte owner, byte humanControlled)',
    'Allocates the first free slot of the 80-entry unit array g_battleUnits (stride 0x34); a slot is free when byte +0 (owner) is zero. Leaves the index in g_lastBattleUnit.'),
  fn('0x0046E767', 'Missile_Spawn', 'verified',
    'undefined4 Missile_Spawn(byte owner, int x, int y, int tx, int ty)',
    'Allocates one of the 100 slots of g_missiles (stride 0x4C) and sets its start and target positions in 1/32-cell units. Used for arrows, bolts, catapult shot, thrown oil, fire and falling figures.'),
  fn('0x0046EBAE', 'BattleUnit_Clear', 'verified', 'void BattleUnit_Clear(int rec)',
    'Zeroes one 0x34-byte battle unit record.'),
  fn('0x0046EB3F', 'BattleMan_Clear', 'verified', 'void BattleMan_Clear(int rec)',
    'Zeroes one 0x1B0-byte battle figure record.'),
  fn('0x0046F0F0', 'BattleMen_ClearAll', 'verified', 'void BattleMen_ClearAll(void)',
    'Zeroes g_battleMen[1..80]. The loop bound 0x51 is what fixes the figure count at 80.'),
  fn('0x0046F18D', 'BattleUnits_ClearAll', 'verified', 'void BattleUnits_ClearAll(void)',
    'Zeroes g_battleUnits[1..80].'),
  fn('0x0046EBE4', 'BattleMan_Destroy', 'verified', 'void BattleMan_Destroy(int man)',
    'Clears the figure off its battlefield cell and zeroes its record.'),
  fn('0x004822ED', 'Battle_UpdateAllMen', 'verified', 'void Battle_UpdateAllMen(void)',
    'Per-frame sweep over g_battleMen[1..80]. Applies burning damage on surface 10/17, ages the figure, then dispatches g_troopTickTable[troopType] - which reloads the per-troop stats and tail-calls g_manStateTable[state].'),
  fn('0x00489401', 'Battle_UpdateAllUnits', 'verified', 'void Battle_UpdateAllUnits(void)',
    'Per-frame sweep over g_battleUnits[1..80]. Recentres each unit on its figures, and runs its order handler unless byte +1 (human controlled) is set. Three dispatch tables: field, siege attacker, siege defender. Counts field +0x14 down from 500 and re-targets at zero.'),
  fn('0x0047EBE8', 'Battle_UpdateMissiles', 'inferred', 'void Battle_UpdateMissiles(void)',
    'Rebuilds the cell -> figure occupancy map for all 80 figures, then steps every missile.'),
  fn('0x00485BB1', 'Missile_UpdateAll', 'verified', 'void Missile_UpdateAll(void)',
    'Steps g_missiles[1..100].'),
  fn('0x00492C8B', 'Missile_Step', 'verified', 'void Missile_Step(void)',
    'Advances the current missile by its steps-per-tick and, when it enters a cell holding an enemy figure, applies the missile damage formula: elevation scaling, minus the target armour, minus the crossbow-vs-engine reduction, floor 2, accumulated into the target hits pool; every 100 hits kills one man. See docs/battle.md.'),
  fn('0x00494908', 'Melee_Tick', 'verified', 'void Melee_Tick(void)',
    'One tick of a melee duel. The attacker decrements the defender recovery counter; when it expires the defender takes the attacker melee attack value into its hits pool, and once per exchange the attacker heavy-blow bonus as well. 100 hits kills one man; the attacker role swaps when the exchange counter runs out.'),
  fn('0x0049459A', 'BattleMan_BurnTick', 'inferred', 'void BattleMan_BurnTick(int man)',
    'Adds 3/6/9/12 hits per tick (1/3/5/7 for siege engines) by battlefield size class to a figure standing on a burning cell, +1/+2 more if the owner is human-controlled. Threshold 100 (160 for engines) kills one man.'),
  fn('0x00481ABB', 'BattleMan_RecomputeStrength', 'verified', 'void BattleMan_RecomputeStrength(int man)',
    'Sets the figure strength band 0..3 by comparing its remaining men against g_strengthBand1/2/3 (75%, 50%, ~19-25% of a full figure), then loads its melee attack value from g_meleeAttackTable[troopType][band].'),
  fn('0x0047F42D', 'Battle_LoadStrengthBands', 'verified', 'void Battle_LoadStrengthBands(void)',
    'Loads the three strength-band thresholds for the current battlefield size class from g_strengthBandTable.'),
  fn('0x00483337', 'BattleMan_FireMissile', 'verified', 'void BattleMan_FireMissile(void)',
    'Missile reload and fire. Acquires a target 10 ticks before the reload interval expires, then spawns a missile whose power is the figure missile damage scaled by its strength band (full, 4/5, 3/4, 1/2).'),
  fn('0x004832EA', 'BattleMan_StateIdle', 'verified', 'void BattleMan_StateIdle(void)',
    'Figure state 5. Advances the animation, and fires if the figure has a missile weapon.'),
  fn('0x00483CE1', 'BattleMan_LookForMelee', 'verified', 'void BattleMan_LookForMelee(void)',
    'Figure state 7. If an adjacent enemy exists, locks both figures into state 4 facing each other, one as attacker and one as defender; otherwise falls back to idle or missile search.'),
  fn('0x004831D8', 'BattleMan_StateMelee', 'verified', 'void BattleMan_StateMelee(void)',
    'Figure state 4. Drops out if the opponent is gone or dead, otherwise runs Melee_Tick.'),
  fn('0x00494E3F', 'Melee_FindAdjacentEnemy', 'verified', 'undefined4 Melee_FindAdjacentEnemy(void)',
    'Tests the eight neighbouring cells in the order N, NW, NE, W, E, SW, SE, S and returns the direction of the first live enemy figure, or 8. Siege engines (troop types 7..10) are never returned.'),
  fn('0x004956CC', 'Missile_FindTarget', 'verified', 'bool Missile_FindTarget(int range, int man, int unit)',
    'Nearest live enemy figure within `range` by Manhattan distance, capped at 160. The unit ordered target is forced to distance 0; siege-engine targets get a +35 distance penalty.'),
  fn('0x00494D08', 'Melee_ResetExchange', 'inferred', 'void Melee_ResetExchange(int man)',
    'Sets how long this figure holds the attacking role in a duel, from its animation class: 0, 40, 80, 80 or 120 ticks.'),
  fn('0x00494DF9', 'Melee_ResetRecovery', 'inferred', 'void Melee_ResetRecovery(int man)',
    'Adds the figure recovery interval (+0x18B) to its recovery counter. That interval is the rate at which the figure can be hit in melee, so it is the real melee defence: peasants and archers 6 ticks, crossbowmen 8, macemen and swordsmen 12, knights 16, pikemen 30.'),
  fn('0x0048F1DD', 'BattleMan_Step', 'verified', 'int BattleMan_Step(int noInterrupt)',
    'Movement. Waits g_troopBattleStats[type].moveDelay ticks per sub-step, accumulates 2 per step until 17, then takes the next path direction and calls BattleMan_TryStepDir. Knights have delay 0 and pikemen 4, which is why knights are fastest and pikemen slowest.'),
  fn('0x00490616', 'BattleMan_TryStepDir', 'verified', 'undefined4 BattleMan_TryStepDir(undefined4 dir)',
    'Turns a direction 0..7 into a neighbouring cell offset, clamps at the map edge and calls Cell_TryEnter.'),
  fn('0x00490A44', 'Cell_TryEnter', 'verified', 'undefined4 Cell_TryEnter(int cellOffset)',
    'Decides whether a figure may enter a battlefield cell: 1 free, 0 blocked by a friendly figure or flag 0x40, 2 impassable (flags 0x10/0x80, or an elevation change of more than 1), 5 flag 0x20 for a non-zero side, 999 enemy figure present.'),
  fn('0x004972F9', 'Melee_AdjacentEnemyDir', 'verified', 'int Melee_AdjacentEnemyDir(int x, int y, int cellOffset)',
    'Scans the eight neighbours via g_cellNeighbourOffsets and returns the direction of an enemy figure standing at the same elevation, or 8.'),
  fn('0x0046F434', 'Dir_FromDelta', 'verified', 'undefined4 Dir_FromDelta(int x, int y, int tx, int ty)',
    'Eight-way direction from (x,y) to (tx,ty): 0 N, 1 NE, 2 E, 3 SE, 4 S, 5 SW, 6 W, 7 NW, 8 same cell. This is the encoding of the figure facing byte.'),
  fn('0x00404EAD', 'Dist_Manhattan', 'verified', 'int Dist_Manhattan(int x, int y, int tx, int ty)',
    'Returns |dx| + |dy| and leaves the two absolute deltas in g_absDx and g_absDy.'),
  fn('0x00404F4C', 'Dist_Chebyshev', 'verified', 'int Dist_Chebyshev(int x, int y, int tx, int ty)',
    'Returns max(|dx|, |dy|) and leaves the two absolute deltas in g_absDx and g_absDy.'),
  fn('0x00404E4B', 'Table_Lookup', 'verified', 'int Table_Lookup(int x, int * pairs, int count, int dflt)',
    'Generic (threshold, value) ladder: returns the value of the first pair whose threshold exceeds x, else the default. Used for the battlefield size class and the men-per-figure scale.'),
  fn('0x0047B8B2', 'Battlefield_BuildFromSkr', 'verified', 'void Battlefield_BuildFromSkr(void)',
    'Loads one 80x80 .skr terrain layer and expands it into the 8-byte-per-cell battlefield, including bridge parts and the two 12-slot deployment marker arrays. See docs/formats/skr.md.'),
  fn('0x0047AAA3', 'Battlefield_BuildRandom', 'inferred', 'void Battlefield_BuildRandom(void)',
    'The open-field battlefield generator: writes the same cell array and the same deployment slot arrays as Battlefield_BuildFromSkr, but from the campaign map rather than a .skr layer.'),
  fn('0x0047C4BA', 'Battlefield_BuildCastle', 'inferred', 'void Battlefield_BuildCastle(int castle)',
    'The siege battlefield builder; the third writer of the cell array.'),
  fn('0x0042D806', 'Skr_ReadMap', 'verified', 'void Skr_ReadMap(int index, void * dst)',
    'Reads one .skr terrain layer: 0x1900 bytes at file offset index * 0x1900 + 0x1674. See docs/formats/skr.md.'),
  fn('0x0048169E', 'Deploy_SlotForUnit', 'verified', 'void Deploy_SlotForUnit(int unitOrdinal, int side)',
    'Picks a deployment cell for the n-th unit of a side from the 12-slot marker array: side 0 uses the 0x04 marker slots at 0x00553150, side 4 the 0x0F marker slots at 0x005531B0. There are only 12 slots, so a side with more than 12 units reads past the end.'),
  fn('0x004816F9', 'Deploy_SlotForUnitSiege', 'inferred', 'void Deploy_SlotForUnitSiege(undefined4 unitOrdinal, int troopType)',
    'The castle-defender placement: maps the troop type to one of the marker slots rather than using the unit ordinal, with a rotating fallback list.'),
  fn('0x00481878', 'Formation_OffsetX', 'verified', 'int Formation_OffsetX(int footprint, int rows, int i)',
    'Column offset of figure i in a units rectangle: (i / rows) * footprint.'),
  fn('0x00481906', 'Formation_OffsetY', 'verified', 'int Formation_OffsetY(int footprint, int rows, uint i, int side)',
    'Row offset of figure i: (i % rows) * footprint, negated for side 0 so both sides face each other.'),
  fn('0x004891AD', 'BattleUnit_Recentre', 'verified', 'void BattleUnit_Recentre(int unit)',
    'Sets the unit position to the centre of the bounding box of its live figures.'),
  fn('0x00479E90', 'BattleUnit_Order', 'verified',
    'void BattleUnit_Order(int unit, int x, int y, int attackTarget, int fromPlayer, int facing)',
    'Gives a battle unit a destination. Missile units stop short of the target by (range/8 - 3) cells; a unit that mixes missile and melee figures is split into two units.'),
  fn('0x0048143B', 'BattleUnit_Classify', 'verified', 'void BattleUnit_Classify(int unit)',
    'Recomputes the unit category from the troop types it still contains: catapult 5, tower 6, ram 7, oil 8, any missile figure 1, otherwise 3. The category selects the order handler.'),
  fn('0x00424992', 'BattleDebug_Panel', 'verified', 'void BattleDebug_Panel(void)',
    'The developers\' own battle debug overlay. It prints figure and unit fields beside their original labels - FIGURE / map x / map y / tg x / tg y / routed / hold it / state / on route / hits / walking / barred / target / dirc / delay / dly state / targeted / selected / selctd seen / polar dirc / mov straff, and GROUP / re targ / map x / map y / targ x / targ y / orders / firing. This is the primary evidence for the field names in docs/battle.md.'),
  fn('0x0042AC0C', 'Troops_Load', 'verified', 'uint Troops_Load(void)',
    'Parses TROOPS.ENG / TROOPS2.ENG / TROOPS3.ENG into g_troopsTable. The in-memory layout is short[35][2][5][11] - side outer (stride 0x6E), difficulty inner (stride 0x16) - and difficulty groups 0,1,3,4 are then overwritten with Normal at +16%, +8%, -8% and -16% on troop types 0..6 only.'),
  fn('0x0042BF46', 'Skirmish_FillArmies', 'verified', 'void Skirmish_FillArmies(void)',
    'Copies one row of g_troopsTable into the two army records used by the battle, choosing the side by whether the player is the attacker and the difficulty column per player, then recomputes each army total men (+0x168) and autocalc strength.'),
  fn('0x0042B7F7', 'Skirmish_Setup', 'inferred', 'void Skirmish_Setup(void)',
    'Sets up a stand-alone skirmish: army records 1 and 2, loads BATTLES.ENG and the TROOPS table, fills both armies.'),
  fn('0x0049005F', 'BattleMen_SwapPlaces', 'verified', 'undefined4 BattleMen_SwapPlaces(void)',
    'When a figure walks into a friendly figure of the same troop type it swaps places with it, carrying position, cell, hits and men across. Returns 2 on a swap.'),
  fn('0x00497437', 'Order_StopShortOfTarget', 'verified',
    'void Order_StopShortOfTarget(int x, int y, int tx, int ty, int range)',
    'Pulls a move destination back so the unit halts (range - 3) cells from its target, leaving the result in g_foundTileX / g_foundTileY. This is how missile units stop at firing range instead of closing.'),
  fn('0x0047095E', 'Path_Search', 'verified',
    'void Path_Search(int mode, int x, int y, int tx, int ty)',
    'The battlefield pathfinder. A uniform-cost breadth-first flood fill over the 80x80 grid with a circular queue: g_pathCost[cell] holds cost+1 from the start, a cell is expanded only after being reached g_pathStepCost[cell] times (that is how terrain cost is charged), and a step is only allowed between cells whose elevation differs by at most 1. Skipped entirely when the target is adjacent or the straight line is clear.'),
  fn('0x00471718', 'Path_SearchSiege', 'inferred',
    'void Path_SearchSiege(int x, int y, int tx, int ty)',
    'The variant of Path_Search used by figures in state 9 - the siege/wall path.'),
  fn('0x00472392', 'Path_Extract', 'verified',
    'int Path_Extract(int x, int y, int tx, int ty)',
    'Walks the g_pathCost field downhill from the destination back to the start, writing the route into g_pathWaypoints as (x,y) byte pairs and returning its length. Ties are broken towards the straight-line direction. Returns 0 for no path and 150 for adjacent or over-long.'),
  fn('0x00472875', 'BattleMan_SetPath', 'verified',
    'void BattleMan_SetPath(int man, int length)',
    'Copies `length` waypoints out of g_pathWaypoints into the figure own list at +0x38, sets the count at +0x36 and marks the figure "on route".'),
  fn('0x00491A34', 'BattleMan_NextPathDir', 'verified',
    'uint BattleMan_NextPathDir(int man)',
    'Returns the direction towards the figure current waypoint and consumes it. The list is walked from the end, because Path_Extract builds it backwards from the destination.'),
  fn('0x0048A7D9', 'Dest_FindReachableNear', 'verified',
    'undefined4 Dest_FindReachableNear(int fromX, int fromY, int x, int y, int unit)',
    'Expanding-ring search of radius 0..19 around (x,y) for a cell with the same surface type and elevation as the source, leaving it in g_foundTileX / g_foundTileY. Used to fix up a move order that lands on unreachable ground.'),
  fn('0x004710F2', 'Path_LineIsClear', 'inferred',
    'bool Path_LineIsClear(int x, int y, int tx, int ty)',
    'Straight-line passability test; when it succeeds Path_Search does no work at all and the figure walks directly at its target.'),
  fn('0x00471F45', 'Path_BuildBlockedMap', 'inferred', 'void Path_BuildBlockedMap(void)',
    'Refreshes the per-cell blocking map the flood fill reads, from the live figure positions.'),
  fn('0x0048B9C1', 'BattleUnit_OrderToEnemyEnd', 'inferred', 'void BattleUnit_OrderToEnemyEnd(int slot)',
    'Sends the current unit to a slot of the opposing sides deployment marker - side 0 to the 0x0F marker, side 4 to the 0x04 marker. Together with Deploy_SlotForUnit this establishes that side 0 deploys at the 0x04 marker and side 4 at the 0x0F marker.'),
];

const globals = [
  gv('0x00554480', 'g_battleMen', 'verified',
    'Battle figure array, 80 records of 0x1B0 bytes, index 1..80 (0 unused). A figure is one drawn man representing g_menPerFigure real soldiers. +0x09 selected, +0x12 troop type, +0x13 owner is human, +0x18 facing 0..7, +0x1C cell byte offset, +0x20/+0x22 x,y, +0x24/+0x26 target x,y, +0x2C owner (0 = free slot), +0x31 state, +0x172 armour, +0x174 target figure, +0x178 owning unit, +0x17A side, +0x17E melee opponent, +0x189 move delay, +0x18B melee recovery interval, +0x197 strength band, +0x198 heavy-blow bonus, +0x19A hits, +0x19C melee attack, +0x1A0 men left. Full map in docs/battle.md.'),
  gv('0x00566520', 'g_battleUnits', 'verified',
    'Battle unit array, 80 records of 0x34 bytes, index 1..80 (0 unused). A unit is what the player selects and orders. +0x00 owner (0 = free slot), +0x01 human controlled, +0x02 figure count, +0x03 side (0 or 4), +0x04/+0x06 first and last figure index, +0x08 category, +0x0F firing timer, +0x14 re-target countdown, +0x1A orders, +0x1E/+0x20 position, +0x22/+0x24 target, +0x2C ordered target figure, +0x30 target cell offset.'),
  gv('0x0057A100', 'g_missiles', 'verified',
    'Missile / effect array, 100 records of 0x4C bytes, index 1..100. +0x06 firing figure, +0x08 owner, +0x09 class (1 bow, 2 crossbow, 3 catapult, 5 fire, 7 falling figure), +0x0A/+0x0C position in 1/32 cell, +0x14/+0x16 cell x,y, +0x1C cell byte offset, +0x2F launch elevation, +0x36 distance flown, +0x38 range, +0x40 power.'),
  gv('0x005440E0', 'g_battlefield', 'verified',
    'Battlefield cell array, 80x80 records of 8 bytes, index (y*80 + x)*8. +0 terrain id, +1 flags (0x10 and 0x80 impassable), +2 flags, +3 graphic index, +4 elevation, +5 index of the figure standing here, +6 head of the missile list in this cell, +7 surface type (7 bridge, 10 and 17 burning, 15 woodland).'),
  gv('0x0053E8F8', 'g_curBattleMan', 'verified',
    'Index of the figure currently being updated. The whole figure state machine reads its subject from this global rather than from a parameter.'),
  gv('0x0052EFF4', 'g_otherBattleMan', 'verified',
    'Index of the other figure in the current interaction: the melee opponent, the missile target, or the figure being swapped with.'),
  gv('0x00568458', 'g_curBattleUnit', 'verified',
    'Index of the unit currently being updated by Battle_UpdateAllUnits.'),
  gv('0x0053F014', 'g_lastBattleMan', 'verified',
    'Index of the figure BattleMan_Create just allocated.'),
  gv('0x005530EC', 'g_lastBattleUnit', 'verified',
    'Index of the unit BattleUnit_Alloc just allocated.'),
  gv('0x00568990', 'g_lastMissile', 'verified',
    'Index of the missile Missile_Spawn just allocated.'),
  gv('0x0056D5B4', 'g_curMissile', 'verified',
    'Index of the missile Missile_Step is advancing.'),
  gv('0x00522F6C', 'g_battleSizeClass', 'verified',
    'Battlefield size class 0..8, from the combined army size. It selects g_menPerFigure, the strength-band thresholds, and the burning-damage rate.'),
  gv('0x004EEA9C', 'g_menPerFigure', 'verified',
    'How many real soldiers one drawn figure stands for: 4, 8, 16, 32, 64, 128, 256, 512 or 1024 by size class. Reduced for a small army so that a side always gets at least 9 figures.'),
  gv('0x0053E8FC', 'g_battleIsSiege', 'verified',
    'Non-zero for a siege: selects the castle battlefield builder, the siege unit-order tables and Battle_RaiseSideSiege.'),
  gv('0x0057C8CC', 'g_localPlayer', 'verified',
    'The player index this machine controls. Compared against a unit owner to decide whose units are on the player side.'),
  gv('0x0053E86C', 'g_strengthBand1', 'verified',
    'Men in a figure below which it drops to strength band 1 - 75% of a full figure.'),
  gv('0x00522F54', 'g_strengthBand2', 'verified', 'Band 2 threshold - 50% of a full figure.'),
  gv('0x00522F5C', 'g_strengthBand3', 'verified', 'Band 3 threshold - about 19-25% of a full figure.'),
  gv('0x00591560', 'g_absDx', 'verified', 'Absolute x distance left by Dist_Manhattan / Dist_Chebyshev.'),
  gv('0x0058FEA0', 'g_absDy', 'verified', 'Absolute y distance left by Dist_Manhattan / Dist_Chebyshev.'),
  gv('0x004D4B98', 'g_troopStrengthWeight', 'verified',
    'Seven ints, the autocalc strength weight of one soldier by troop type: peasant 2, crossbowman 16, maceman 8, swordsman 13, pikeman 9, archer 13, knight 22. Used only for army strength comparisons, not by the real-time battle.'),
  gv('0x004D96D0', 'g_troopBattleStats', 'verified',
    'Per troop type, 11 rows of 5 ints: max figures per unit, cell footprint, max figures per formation row, weapon class (index into g_missileStats), move delay in ticks.'),
  gv('0x004D97B0', 'g_missileStats', 'verified',
    'Per weapon class, 4 rows of 5 ints: range in 1/8 cells, reload interval in ticks, sub-steps per tick, damage, sprite-bank offset. Class 0 melee (all zero), 1 bow (120, 50, 4, 50, 0), 2 crossbow (64, 100, 4, 200, 8), 3 catapult (160, 100, 4, 200, 16).'),
  gv('0x004D98F8', 'g_meleeAttackTable', 'verified',
    'Melee attack value by troop type and strength band, 11 rows of 4 shorts. Peasant/crossbow/archer 5,4,3,2; mace and sword 15,12,10,6; pike 10,8,6,5; knight 20,15,11,6; siege engines all zero.'),
  gv('0x004D9658', 'g_menPerFigureTable', 'verified',
    'Nine ints indexed by battlefield size class: 4, 8, 16, 32, 64, 128, 256, 512, 1024 men per drawn figure.'),
  gv('0x004D95D8', 'g_sizeClassLadder', 'verified',
    'Eight (threshold, size class) pairs mapping total men to the battlefield size class: 305, 609, 1217, 2433, 4865, 9729, 19457, 38913, then 8.'),
  gv('0x004D9618', 'g_siegeScaleLadder', 'verified',
    'Eight (threshold, value) pairs giving how many men one siege engine counts as when choosing the size class.'),
  gv('0x004D9800', 'g_strengthBandTable', 'verified',
    'Three ints per battlefield size class: the men-per-figure thresholds for strength bands 1, 2 and 3 - 75%, 50% and about 19-25% of a full figure.'),
  gv('0x004D9870', 'g_raiseOrder', 'verified',
    'The order in which troop types become units in a field battle: ram, oil, knight, sword, mace, pike, crossbow, archer, peasant, tower, catapult.'),
  gv('0x004D98A0', 'g_raiseOrderSiege', 'verified',
    'The castle-defender raise order, eight troop types: oil, archer, crossbow, knight, peasant, sword, mace, pike. Catapults, towers and rams are absent.'),
  gv('0x004D9140', 'g_troopTickTable', 'verified',
    'Eleven function pointers indexed by troop type. Each reloads that troop per-tick constants - animation set, recovery interval, heavy-blow bonus, armour - and then tail-calls g_manStateTable[state].'),
  gv('0x004D9170', 'g_manStateTable', 'verified',
    'Eighteen figure-state handlers indexed by figure byte +0x31. Known: 2 dead, 4 melee, 5 idle/firing, 6 blocked, 7 look for melee, 12 siege engine attacking, 17 closing to attack.'),
  gv('0x004D91B8', 'g_unitOrderTableField', 'verified',
    'Five unit order handlers for a field battle, indexed by unit category 0..4.'),
  gv('0x004D91D0', 'g_unitOrderTableSiegeAtt', 'verified',
    'Nine unit order handlers for the siege attacker (unit side non-zero), indexed by unit category 0..8.'),
  gv('0x004D91F8', 'g_unitOrderTableSiegeDef', 'verified',
    'Eleven unit order handlers for the siege defender (unit side zero), indexed by unit category 0..10.'),
  gv('0x004D8588', 'g_cellNeighbourOffsets', 'verified',
    'Eight ints, the battlefield cell byte offsets of the neighbours in direction order 0..7: -0x280, -0x278, +8, +0x288, +0x280, +0x278, -8, -0x288.'),
  gv('0x00516AC0', 'g_troopsTable', 'verified',
    'The parsed TROOPS*.ENG table: short[35][2][5][11], row stride 0xDC, side stride 0x6E, difficulty stride 0x16. See docs/formats/eng.md and the correction in docs/battle.md.'),
  gv('0x0051FAE0', 'g_troopsAdvantage', 'verified',
    'The per-battle defensive advantage 0..10, one per TROOPS*.ENG row.'),
  gv('0x004D49B8', 'g_troopsRowBase', 'inferred',
    'Four ints, 0/10/20/35: the first g_troopsTable row for each battle category.'),
  gv('0x00568210', 'g_battleArmyA', 'verified',
    'Index into g_units of the first army in the current battle. It is raised on side 4.'),
  gv('0x00568218', 'g_battleArmyB', 'verified',
    'Index into g_units of the second army. It is raised on side 0, and is the side the castle-defender path is applied to in a siege.'),
  gv('0x0054409C', 'g_battleStrengthA', 'verified',
    'Autocalc strength of army A: sum of count[t] * g_troopStrengthWeight[t] over troop types 0..6.'),
  gv('0x00553FC0', 'g_battleStrengthB', 'verified', 'Autocalc strength of army B.'),
  gv('0x00553E68', 'g_debugSelectedMan', 'inferred',
    'The figure index BattleDebug_Panel prints.'),
  gv('0x00504030', 'g_pathCost', 'verified',
    'Pathfinder cost field, u16 per battlefield cell, index y*80 + x. 0 means unvisited, 1 the start cell, 998 (0x3E6) blocked.'),
  gv('0x004FA820', 'g_pathQueue', 'verified',
    'Pathfinder frontier, a circular queue of 0x1900 cell indices with head g_pathQueueHead and tail g_pathQueueTail.'),
  gv('0x00503018', 'g_pathQueueHead', 'verified', 'Read cursor of g_pathQueue.'),
  gv('0x004F981C', 'g_pathQueueTail', 'verified', 'Write cursor of g_pathQueue; wraps at 0x1900.'),
  gv('0x004F2770', 'g_pathStepCost', 'inferred',
    'Per-cell step cost the flood fill charges: a cell is only expanded once it has been reached this many times.'),
  gv('0x004F6470', 'g_pathVisitCount', 'verified',
    'How many times the flood fill has reached each cell, compared against g_pathStepCost.'),
  gv('0x004F7D80', 'g_pathElevation', 'inferred',
    'Per-cell elevation the flood fill and Path_Extract read; a step is only allowed between cells differing by at most 1.'),
  gv('0x004F9680', 'g_pathWaypoints', 'verified',
    'Scratch route built by Path_Extract: (x, y) byte pairs, at most 150, ordered destination-first. BattleMan_SetPath copies it into the figure.'),
  gv('0x004D6C98', 'g_cellIndexNeighbours', 'verified',
    'Eight ints, the battlefield cell-index (not byte) deltas in direction order 0..7: -0x50, -0x4F, +1, +0x51, +0x50, +0x4F, -1, -0x51.'),
];

// Splice the entries in as text, so the rest of the file keeps its hand formatting.
const q = (s) => JSON.stringify(s);
const fnText = (e) => '    {\n' +
  '      "addr": ' + q(e.addr) + ', "name": ' + q(e.name) + ', "section": ' + q(e.section) +
  ', "confidence": ' + q(e.confidence) + ',\n' +
  '      "signature": ' + q(e.signature) + ',\n' +
  '      "comment": ' + q(e.comment) + '\n    }';
const gvText = (e) => '    { "addr": ' + q(e.addr) + ', "name": ' + q(e.name) +
  ', "section": ' + q(e.section) + ', "confidence": ' + q(e.confidence) + ',\n' +
  '      "comment": ' + q(e.comment) + ' }';

let text = fs.readFileSync(file, 'utf8');
if (text.includes('"' + S + '"')) {
  console.error('docs/symbols.json already carries a "' + S + '" section - nothing to do.');
  process.exit(1);
}

text = text.replace('{ "id": "units",    "title": "Units, merchants and counties" }\n  ],',
  '{ "id": "units",    "title": "Units, merchants and counties" },\n' +
  '    { "id": "battle",   "title": "Battle simulation" }\n  ],');

const fnAnchor = '\n  ],\n\n  "globals": [';
text = text.replace(fnAnchor, ',\n\n' + functions.map(fnText).join(',\n') + fnAnchor);

const gvAnchor = ' }\n  ]\n}\n';
text = text.replace(gvAnchor, ' },\n\n' + globals.map(gvText).join(',\n') + '\n  ]\n}\n');

JSON.parse(text);   // fail loudly rather than write broken JSON
fs.writeFileSync(file, text);
const root = JSON.parse(text);
console.log('functions ' + root.functions.length + ', globals ' + root.globals.length +
  ', sections ' + root.sections.length);
