#![allow(unused_imports)]
use super::*;
use super::layout_tests::*;
use super::oracle_tests::*;
use super::value_tests::*;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use l2_formats::save::{Save, COUNTY_BASE, COUNTY_STRIDE, REALM_BASE, REALM_STRIDE};
use l2_kingdom::Kingdom;
use l2_scenario::Scenario;

/// The kingdom's value for one element of one row: `(kingdom, county or realm
/// id, element)`.
type Get = fn(&Kingdom, usize, usize) -> i64;

fn at(id: &'static str, get: Get) -> (&'static str, Get) {
    (id, get)
}

/// **Where each claimed row lives in a loaded kingdom.**
///
/// Written by the same hand as the inventory, which `docs/agents.md` warns is
/// the shape of a check that lies
/// neither list is what it is compared against. Both are held to the bytes the
/// original wrote.
fn accessors() -> Vec<(&'static str, Get)> {
    vec![
        at("County+0x000", |k, i, _| k.counties[i].event_fired as i64),
        at("County+0x005", |k, i, _| k.counties[i].owner as i64),
        at("County+0x008", |k, i, _| k.counties[i].industry_share as i64),
        at("County+0x009", |k, i, _| k.counties[i].health_band as i64),
        at("County+0x00B", |k, i, _| k.counties[i].health_meter as i64),
        at("County+0x00C", |k, i, _| k.counties[i].happiness as i64),
        at("County+0x00D", |k, i, _| k.counties[i].happiness_last as i64),
        at("County+0x00E", |k, i, _| k.counties[i].d_hap_tax as i64),
        at("County+0x00F", |k, i, _| k.counties[i].d_hap_tax_local as i64),
        at("County+0x010", |k, i, _| k.counties[i].d_hap_health as i64),
        at("County+0x011", |k, i, _| k.counties[i].d_hap_ration as i64),
        at("County+0x012", |k, i, _| k.counties[i].shown_tax as i64),
        at("County+0x013", |k, i, _| k.counties[i].shown_ration as i64),
        at("County+0x014", |k, i, _| k.counties[i].shown_health as i64),
        at("County+0x015", |k, i, _| k.counties[i].shown_army as i64),
        at("County+0x016", |k, i, _| k.counties[i].tax_hap_other as i64),
        at("County+0x017", |k, i, _| k.counties[i].shown_events as i64),
        at("County+0x018", |k, i, _| k.counties[i].happiness_avg as i64),
        at("County+0x01C", |k, i, _| k.counties[i].happiness_sum as i64),
        at("County+0x020", |k, i, _| k.counties[i].unrest as i64),
        at("County+0x021", |k, i, _| k.counties[i].unrest_warned as i64),
        at("County+0x024", |k, i, _| k.counties[i].population as i64),
        at("County+0x028", |k, i, _| k.counties[i].pop_last as i64),
        at("County+0x02C", |k, i, _| k.counties[i].pop_change_pct as i64),
        at("County+0x030", |k, i, _| k.counties[i].births as i64),
        at("County+0x034", |k, i, _| k.counties[i].deaths as i64),
        at("County+0x038", |k, i, _| k.counties[i].army as i64),
        at("County+0x03C", |k, i, _| k.counties[i].emigrants as i64),
        at("County+0x040", |k, i, _| k.counties[i].immigrants as i64),
        at("County+0x044", |k, i, _| k.counties[i].largest_inflow as i64),
        at("County+0x048", |k, i, e| k.counties[i].inflow_sources[e] as i64),
        at("County+0x058", |k, i, _| k.counties[i].emigrant_destination as i64),
        at("County+0x059", |k, i, _| k.counties[i].largest_inflow_source as i64),
        at("County+0x05A", |k, i, _| k.counties[i].neighbour_count as i64),
        at("County+0x05B", |k, i, _| k.counties[i].change_reason as u8 as i64),
        at("County+0x05C", |k, i, e| k.counties[i].neighbours[e] as i64),
        at("County+0x06C", |k, i, _| k.counties[i].anchor_x as i64),
        at("County+0x06D", |k, i, _| k.counties[i].anchor_y as i64),
        at("County+0x090", |k, i, e| k.counties[i].field_progress[e] as i64),
        at("County+0x0B8", |k, i, _| k.counties[i].pop_band as i64),
        at("County+0x0B9", |k, i, _| k.counties[i].tax_rate as i64),
        at("County+0x0BC", |k, i, _| k.counties[i].tax_collected as i64),
        at("County+0x0C0", |k, i, _| k.counties[i].tax_shown as i64),
        at("County+0x0C4", |k, i, e| k.counties[i].labour[e] as i64),
        at("County+0x0C8", |k, i, e| k.counties[i].labour_wanted[e] as i64),
        at("County+0x0CC", |k, i, e| k.counties[i].labour_useful[e] as i64),
        at("County+0x130", |k, i, e| k.counties[i].labour_share[e] as i64),
        at("County+0x15D", |k, i, _| k.counties[i].ration_achieved as i64),
        at("County+0x15E", |k, i, _| k.counties[i].ration_wanted as i64),
        at("County+0x15F", |k, i, _| k.counties[i].ration_split as i64),
        // `Ration_Apply`'s *Fed* row, in the file's order dairy, grain, meat;
        // `people_fed` returns grain, meat, dairy.
        at("County+0x16C", |k, i, e| {
            let (grain, meat, dairy) = l2_kingdom::ration::people_fed(&k.tables, &k.counties[i]);
            [dairy, grain, meat][e] as i64
        }),
        at("County+0x178", |k, i, _| k.counties[i].grain_eaten as i64),
        at("County+0x17C", |k, i, _| k.counties[i].herd_eaten as i64),
        at("County+0x180", |k, i, _| k.counties[i].grain_available as i64),
        at("County+0x184", |k, i, _| k.counties[i].herd_available as i64),
        at("County+0x194", |k, i, _| k.counties[i].shown_ale as i64),
        at("County+0x198", |k, i, _| k.counties[i].friendly_troops as i64),
        at("County+0x19C", |k, i, _| k.counties[i].enemy_troops as i64),
        at("County+0x1A0", |k, i, _| k.counties[i].merchant_visits as i64),
        at("County+0x1A4", |k, i, _| k.counties[i].merchant_count as i64),
        at("County+0x1A5", |k, i, _| k.counties[i].merchant_unit as i64),
        // A `char` in the original: the byte, not the whole quotient.
        at("County+0x1A6", |k, i, _| {
            l2_kingdom::industry::castle_seasons_left(&k.tables, &k.counties[i]) as u8 as i64
        }),
        at("County+0x1A7", |k, i, _| k.counties[i].sow_shortfall as i64),
        at("County+0x1A8", |k, i, _| k.counties[i].tax_suppressed as i64),
        at("County+0x1AA", |k, i, _| k.counties[i].event_id as i64),
        at("County+0x1AD", |k, i, _| k.counties[i].mercenary_offer as i64),
        at("County+0x1B0", |k, i, _| k.counties[i].castle_switch as i64),
        at("County+0x1BC", |k, i, _| k.counties[i].garrison_unit as i64),
        at("County+0x1C0", |k, i, _| k.counties[i].castle_type as i64),
        at("County+0x1C1", |k, i, _| k.counties[i].castle_building as i64),
        at("County+0x1C2", |k, i, _| k.counties[i].castle_ruined as i64),
        at("County+0x1C3", |k, i, _| k.counties[i].castle_degraded as i64),
        at("County+0x1C4", |k, i, _| k.counties[i].castle_percent as i64),
        at("County+0x1CC", |k, i, _| k.counties[i].castle_work_left as i64),
        at("County+0x1D0", |k, i, _| k.counties[i].castle_stone_owed as i64),
        at("County+0x1D4", |k, i, _| k.counties[i].castle_wood_owed as i64),
        at("County+0x1D8", |k, i, _| k.counties[i].castle_work_total as i64),
        at("County+0x1DC", |k, i, _| k.counties[i].castle_stone_total as i64),
        at("County+0x1E0", |k, i, _| k.counties[i].castle_wood_total as i64),
        at("County+0x1E4", |k, i, _| k.counties[i].siege_scars.moat_filled as i64),
        at("County+0x1E6", |k, i, _| k.counties[i].siege_scars.wall_damage as i64),
        at("County+0x1E8", |k, i, _| k.counties[i].siege_scars.breach_score as i64),
        at("County+0x1EC", |k, i, _| k.counties[i].siege_scars.approach_score as i64),
        at("County+0x1F0", |k, i, _| k.counties[i].siege_scars.ramparts_breached as i64),
        at("County+0x1F1", |k, i, _| k.counties[i].siege_scars.gate_open as i64),
        at("County+0x1F4", |k, i, _| k.counties[i].purse as i64),
        at("County+0x1F9", |k, i, _| k.counties[i].castle_level_left as i64),
        at("County+0x1FB", |k, i, _| k.counties[i].event_population_pct as i64),
        at("County+0x1FC", |k, i, _| k.counties[i].event_grain_pct as i64),
        at("County+0x1FD", |k, i, _| k.counties[i].event_herd_pct as i64),
        at("County+0x1FE", |k, i, _| k.counties[i].farm_style as i64),
        at("County+0x15A", |k, i, _| k.counties[i].pasture_cursor as i64),
        at("County+0x15B", |k, i, _| k.counties[i].blight_cursor as i64),
        at("County+0x1FF", |k, i, _| k.counties[i].fields_fallow as i64),
        at("County+0x200", |k, i, _| k.counties[i].fields_cattle as i64),
        at("County+0x201", |k, i, _| k.counties[i].fields_grain as i64),
        at("County+0x202", |k, i, _| k.counties[i].fields_grain_sown as i64),
        at("County+0x206", |k, i, _| k.counties[i].fields_grain_standing as i64),
        at("County+0x203", |k, i, _| k.counties[i].fields_waste as i64),
        at("County+0x204", |k, i, _| k.counties[i].fields_reclaiming as i64),
        at("County+0x208", |k, i, _| k.counties[i].fertility as i64),
        at("County+0x20C", |k, i, _| k.counties[i].reclaim_fields_finishing as i64),
        at("County+0x214", |k, i, _| k.counties[i].reclaim_seasons_to_next as i64),
        at("County+0x219", |k, i, _| k.counties[i].ale_happiness_given as i64),
        at("County+0x21B", |k, i, _| k.counties[i].weather.index() as i64),
        at("County+0x21D", |k, i, _| k.counties[i].dryness as i64),
        at("County+0x224", |k, i, _| k.counties[i].grain as i64),
        at("County+0x22C", |k, i, _| k.counties[i].grain_change_expected as i64),
        at("County+0x230", |k, i, _| k.counties[i].grain_sown_expected as i64),
        at("County+0x240", |k, i, e| k.counties[i].crop[e] as i64),
        at("County+0x250", |k, i, _| k.counties[i].herd as i64),
        at("County+0x258", |k, i, _| k.counties[i].herd_change_expected as i64),
        at("County+0x25C", |k, i, _| k.counties[i].herd_crowding as i64),
        at("County+0x268", |k, i, _| k.counties[i].herd_births_expected as i64),
        at("County+0x26C", |k, i, _| k.counties[i].herd_deaths_expected as i64),
        at("County+0x24C", |k, i, _| k.counties[i].grain_weather_change as i64),
        at("County+0x270", |k, i, _| k.counties[i].herd_weather_change as i64),
        at("County+0x274", |k, i, _| k.counties[i].herd_event_change as i64),
        at("County+0x278", |k, i, _| k.counties[i].grain_event_change as i64),
        at("County+0x280", |k, i, e| l2_kingdom::industry::panel_figures(&k.tables, &k.counties[i])[e] as i64),
        at("County+0x290", |k, i, _| k.counties[i].weapon_type as i64),
        at("County+0x294", |k, i, e| k.counties[i].industry[e].efficiency as i64),
        at("County+0x295", |k, i, e| k.counties[i].industry[e].has_resource as i64),
        at("County+0x296", |k, i, e| k.counties[i].industry[e].disabled_seasons as i64),
        at("County+0x297", |k, i, e| k.counties[i].industry[e].enabled as i64),
        at("County+0x29E", |k, i, e| k.counties[i].industry[e].capacity as i64),
        at("County+0x2A0", |k, i, e| k.counties[i].industry[e].total as i64),
        // The snapshot is not a field of `Industry`:
        // the pass takes, so the snapshot is what makes that difference.
        at("County+0x2A4", |k, i, e| {
            let ind = &k.counties[i].industry[e];
            (ind.total - ind.output) as i64
        }),
        at("County+0x2A8", |k, i, e| k.counties[i].industry[e].next_season as i64),
        at("County+0x2F4", |k, i, _| k.counties[i].levy_surcharge as i64),
        at("County+0x2F8", |k, i, _| k.counties[i].event_population_swing as i64),
        at("County+0x2FC", |k, i, _| k.counties[i].grain_grown_expected as i64),
        at("Realm+0x000", |k, i, _| k.realms[i].ai_step as i64),
        at("Realm+0x004", |k, i, _| k.realms[i].strength as i64),
        at("Realm+0x005", |k, i, _| k.realms[i].is_human as i64),
        at("Realm+0x007", |k, i, _| k.realms[i].lord as i64),
        at("Realm+0x00A", |k, i, _| k.realms[i].shield_index as i64),
        at("Realm+0x00C", |k, i, _| k.realms[i].mean_happiness as i64),
        at("Realm+0x010", |k, i, _| k.realms[i].population_total as i64),
        at("Realm+0x014", |k, i, _| k.realms[i].population_mean as i64),
        at("Realm+0x018", |k, i, _| k.realms[i].population_last as i64),
        at("Realm+0x01C", |k, i, _| k.realms[i].offer_pending as i64),
        at("Realm+0x028", |k, i, _| k.realms[i].tax_hap_empire as i64),
        at("Realm+0x029", |k, i, _| k.realms[i].county_count as i64),
        at("Realm+0x02A", |k, i, _| k.realms[i].peak_counties as i64),
        at("Realm+0x02B", |k, i, _| k.realms[i].rank as i64),
        at("Realm+0x02C", |k, i, _| k.realms[i].army_count as i64),
        at("Realm+0x02D", |k, i, e| k.campaign.names.counters(i as u8)[e] as i64),
        at("Realm+0x045", |k, i, _| k.realms[i].muster_timer as i64),
        at("Realm+0x048", |k, i, _| k.realms[i].threat_realm as i64),
        at("Realm+0x04B", |k, i, _| k.realms[i].attack_county as i64),
        at("Realm+0x04C", |k, i, _| {
            k.realms[i].score_inputs[l2_kingdom::tables::SCORE_INPUT_CASTLES] as i64
        }),
        at("Realm+0x050", |k, i, _| k.realms[i].score as i64),
        at("Realm+0x054", |k, i, _| k.realms[i].total_men as i64),
        at("Realm+0x058", |k, i, _| k.realms[i].mean_health as i64),
        at("Realm+0x060", |k, i, _| k.realms[i].share_of_map_pct as i64),
        at("Realm+0x06C", |k, i, _| k.realms[i].weapon_rota as i64),
        at("Realm+0x070", |k, i, e| k.realms[i].want[e] as i64),
        at("Realm+0x080", |k, i, _| k.realms[i].ally_candidate as i64),
        at("Realm+0x081", |k, i, _| k.realms[i].ally as i64),
        at("Realm+0x084", |k, i, e| k.realms[i].pairs[e].standing as i64),
        at("Realm+0x085", |k, i, e| k.realms[i].pairs[e].allied as i64),
        at("Realm+0x086", |k, i, e| k.realms[i].pairs[e].grudge as i64),
        at("Realm+0x087", |k, i, e| k.realms[i].pairs[e].warnings_sent as i64),
        at("Realm+0x088", |k, i, e| k.realms[i].pairs[e].at_war as i64),
        at("Realm+0x089", |k, i, e| k.realms[i].pairs[e].compliments_from as i64),
        at("Realm+0x08C", |k, i, e| k.realms[i].pairs[e].best_gift as i64),
        at("Realm+0x090", |k, i, e| k.realms[i].pairs[e].has_mail as i64),
        at("Realm+0x091", |k, i, e| k.realms[i].pairs[e].help_price_multiple as i64),
        at("Realm+0x0E5", |k, i, _| k.realms[i].muster_county as i64),
        at("Realm+0x0E6", |k, i, _| k.realms[i].raid_county as i64),
        at("Realm+0x0E8", |k, i, _| k.realms[i].target_county as i64),
        at("Realm+0x0E9", |k, i, _| k.realms[i].taunt_timer as i64),
        at("Realm+0x0EA", |k, i, _| k.realms[i].taunt_stage as i64),
        at("Realm+0x0EB", |k, i, _| k.realms[i].war_target as i64),
        at("Realm+0x0EC", |k, i, _| k.realms[i].offer_timer as i64),
        at("Realm+0x0ED", |k, i, _| k.realms[i].crowned_once as i64),
        at("Realm+0x0F4", |k, i, e| k.realms[i].tax_ledger[e] as i64),
        at("Realm+0x0FC", |k, i, _| k.realms[i].wages as i64),
        at("Realm+0x104", |k, i, _| k.realms[i].trade_spent_a as i64),
        at("Realm+0x108", |k, i, _| k.realms[i].trade_spent_b as i64),
        at("Realm+0x10C", |k, i, _| k.realms[i].trade_received_a as i64),
        at("Realm+0x110", |k, i, _| k.realms[i].trade_received_b as i64),
        at("Realm+0x118", |k, i, _| k.realms[i].gold as i64),
        at("Realm+0x120", |k, i, _| k.realms[i].iron as i64),
        at("Realm+0x128", |k, i, _| k.realms[i].stone as i64),
        at("Realm+0x130", |k, i, _| k.realms[i].wood as i64),
        at("Realm+0x138", |k, i, _| k.realms[i].weapons_total() as i64),
        at("Realm+0x140", |k, i, e| k.realms[i].weapons[e] as i64),
        at("Realm+0x158", |k, i, _| k.realms[i].bankrupt_stage as i64),
        at("Realm+0x159", |k, i, _| k.realms[i].voice_rotation as i64),
        at("Realm+0x15A", |k, i, _| k.realms[i].raid_timer as i64),
        at("Realm+0x15C", |k, i, _| k.tax_expected(i as u8) as i64),
    ]
}

