#![allow(unused_imports)]
use super::*;
use super::ladders::*;
use super::*;

impl Tables {
    pub const DEFAULT: Tables = Tables {
        food: FoodTable {
            dairy_per_head: DAIRY_PER_HEAD,
            food_per_head: FOOD_PER_HEAD,
            food_per_sack: FOOD_PER_SACK,
        },
        grain: GrainTable {
            yield_per_sack: GRAIN_YIELD_PER_SACK,
            max_sacks_per_field: GRAIN_MAX_SACKS_PER_FIELD,
            labour_divisor_advanced: GRAIN_LABOUR_DIVISOR_ADVANCED,
            labour_divisor_basic: GRAIN_LABOUR_DIVISOR_BASIC,
            grow_per_worker_advanced: GRAIN_GROW_PER_WORKER_ADVANCED,
            harvest_per_worker_advanced: GRAIN_HARVEST_PER_WORKER_ADVANCED,
        },
        field: FieldTable {
            progress_max: FIELD_PROGRESS_MAX,
            reclaim_per_season: FIELD_RECLAIM_PER_SEASON,
        },
        event: EventTable {
            population_cap_pct: EVENT_POPULATION_CAP_PCT,
            first_year: EVENT_FIRST_YEAR,
        },
        season: [
            SeasonRow { death_rate: DEATH_RATE_BY_SEASON[0], dryness: DRYNESS_BY_SEASON[0] },
            SeasonRow { death_rate: DEATH_RATE_BY_SEASON[1], dryness: DRYNESS_BY_SEASON[1] },
            SeasonRow { death_rate: DEATH_RATE_BY_SEASON[2], dryness: DRYNESS_BY_SEASON[2] },
            SeasonRow { death_rate: DEATH_RATE_BY_SEASON[3], dryness: DRYNESS_BY_SEASON[3] },
            SeasonRow { death_rate: DEATH_RATE_BY_SEASON[4], dryness: DRYNESS_BY_SEASON[4] },
        ],
        ration: [
            RationRow {
                divisor: RATION_TABLE[0].0,
                multiplier: RATION_TABLE[0].1,
                health_delta: HEALTH_DELTA[0],
            },
            RationRow {
                divisor: RATION_TABLE[1].0,
                multiplier: RATION_TABLE[1].1,
                health_delta: HEALTH_DELTA[1],
            },
            RationRow {
                divisor: RATION_TABLE[2].0,
                multiplier: RATION_TABLE[2].1,
                health_delta: HEALTH_DELTA[2],
            },
            RationRow {
                divisor: RATION_TABLE[3].0,
                multiplier: RATION_TABLE[3].1,
                health_delta: HEALTH_DELTA[3],
            },
            RationRow {
                divisor: RATION_TABLE[4].0,
                multiplier: RATION_TABLE[4].1,
                health_delta: HEALTH_DELTA[4],
            },
            RationRow {
                divisor: RATION_TABLE[5].0,
                multiplier: RATION_TABLE[5].1,
                health_delta: HEALTH_DELTA[5],
            },
        ],
        tax_happiness_other: TAX_HAPPINESS_OTHER,
        ration_happiness_slope: 3,
        ration_happiness_offset: -8,
        health: [
            HealthBandRow { happiness: HEALTH_HAPPINESS[0], death_rate: DEATH_RATE_BY_HEALTH[0] },
            HealthBandRow { happiness: HEALTH_HAPPINESS[1], death_rate: DEATH_RATE_BY_HEALTH[1] },
            HealthBandRow { happiness: HEALTH_HAPPINESS[2], death_rate: DEATH_RATE_BY_HEALTH[2] },
            HealthBandRow { happiness: HEALTH_HAPPINESS[3], death_rate: DEATH_RATE_BY_HEALTH[3] },
            HealthBandRow { happiness: HEALTH_HAPPINESS[4], death_rate: DEATH_RATE_BY_HEALTH[4] },
        ],
        health_band_ladder: HEALTH_BAND_LADDER,
        population: PopulationTable {
            birth_rate_ladder: BIRTH_RATE_LADDER,
            happiness_factor_ladder: [(26, 25), (51, 50), (76, 75), (100, 100), (i32::MAX, 120)],
        },
        weather: [
            WeatherRow { herd_pct: HERD_WEATHER_PCT[0] },
            WeatherRow { herd_pct: HERD_WEATHER_PCT[1] },
            WeatherRow { herd_pct: HERD_WEATHER_PCT[2] },
            WeatherRow { herd_pct: HERD_WEATHER_PCT[3] },
            WeatherRow { herd_pct: HERD_WEATHER_PCT[4] },
            WeatherRow { herd_pct: HERD_WEATHER_PCT[5] },
        ],
        herd: HerdTable {
            labour_per_head: HERD_LABOUR_PER_HEAD,
            staffing_max: HERD_STAFFING_MAX,
            understaffing_divisor: HERD_UNDERSTAFFING_DIVISOR,
            crowding: [
                HerdCrowdingRow {
                    density_max: HERD_CROWDING[0].0,
                    level: HERD_CROWDING[0].1,
                    death_rate: HERD_CROWDING[0].2,
                    birth_rate: HERD_CROWDING[0].3,
                },
                HerdCrowdingRow {
                    density_max: HERD_CROWDING[1].0,
                    level: HERD_CROWDING[1].1,
                    death_rate: HERD_CROWDING[1].2,
                    birth_rate: HERD_CROWDING[1].3,
                },
                HerdCrowdingRow {
                    density_max: HERD_CROWDING[2].0,
                    level: HERD_CROWDING[2].1,
                    death_rate: HERD_CROWDING[2].2,
                    birth_rate: HERD_CROWDING[2].3,
                },
                HerdCrowdingRow {
                    density_max: HERD_CROWDING[3].0,
                    level: HERD_CROWDING[3].1,
                    death_rate: HERD_CROWDING[3].2,
                    birth_rate: HERD_CROWDING[3].3,
                },
            ],
            small_bonus: HERD_SMALL_BONUS,
            no_pasture_density: HERD_NO_PASTURE_DENSITY,
            no_pasture_kill_all_below: HERD_NO_PASTURE_KILL_ALL_BELOW,
            no_pasture_divisor: HERD_NO_PASTURE_DIVISOR,
            calving_season: HERD_CALVING_SEASON,
            culling_season: HERD_CULLING_SEASON,
            season_bonus: HERD_SEASON_BONUS,
        },
        castle: CastleTable {
            starting_type: CASTLE_STARTING_TYPE,
            tax_base: CASTLE_TAX_BASE,
            tax_bonus_pct: CASTLE_TAX_BONUS_PCT,
            cost: CASTLE_COST,
            workforce: CASTLE_WORKFORCE,
            garrison_cap: CASTLE_GARRISON_CAP,
            free_archers: CASTLE_FREE_ARCHERS,
        },
        commodity: [
            CommodityRow { job: JOB_WOOD_CUTTING, divisor: 1, base_efficiency: 20 },
            CommodityRow { job: JOB_IRON_MINING, divisor: 1, base_efficiency: 15 },
            CommodityRow { job: JOB_BLACKSMITH, divisor: 4, base_efficiency: 15 },
            CommodityRow { job: JOB_STONE_QUARRYING, divisor: 2, base_efficiency: 15 },
        ],
        job: JobTable {
            count: JOB_COUNT,
            iron_mining: JOB_IRON_MINING,
            stone_quarrying: JOB_STONE_QUARRYING,
            wood_cutting: JOB_WOOD_CUTTING,
            blacksmith: JOB_BLACKSMITH,
            grain_farming: JOB_GRAIN_FARMING,
            cattle_farming: JOB_CATTLE_FARMING,
            castle_building: JOB_CASTLE_BUILDING,
        },
        weapon: [
            WeaponRow { wood: WEAPON_COST[0].0, iron: WEAPON_COST[0].1 },
            WeaponRow { wood: WEAPON_COST[1].0, iron: WEAPON_COST[1].1 },
            WeaponRow { wood: WEAPON_COST[2].0, iron: WEAPON_COST[2].1 },
            WeaponRow { wood: WEAPON_COST[3].0, iron: WEAPON_COST[3].1 },
            WeaponRow { wood: WEAPON_COST[4].0, iron: WEAPON_COST[4].1 },
            WeaponRow { wood: WEAPON_COST[5].0, iron: WEAPON_COST[5].1 },
        ],
        good: [
            GoodRow { sell_price: GOOD_SELL_PRICE[0] },
            GoodRow { sell_price: GOOD_SELL_PRICE[1] },
            GoodRow { sell_price: GOOD_SELL_PRICE[2] },
            GoodRow { sell_price: GOOD_SELL_PRICE[3] },
            GoodRow { sell_price: GOOD_SELL_PRICE[4] },
            GoodRow { sell_price: GOOD_SELL_PRICE[5] },
            GoodRow { sell_price: GOOD_SELL_PRICE[6] },
            GoodRow { sell_price: GOOD_SELL_PRICE[7] },
            GoodRow { sell_price: GOOD_SELL_PRICE[8] },
            GoodRow { sell_price: GOOD_SELL_PRICE[9] },
            GoodRow { sell_price: GOOD_SELL_PRICE[10] },
            GoodRow { sell_price: GOOD_SELL_PRICE[11] },
            GoodRow { sell_price: GOOD_SELL_PRICE[12] },
            GoodRow { sell_price: GOOD_SELL_PRICE[13] },
            GoodRow { sell_price: GOOD_SELL_PRICE[14] },
        ],
        wages: WageTable {
            divisor_human: WAGE_DIVISOR_HUMAN,
            divisor_ai: WAGE_DIVISOR_AI,
            bankrupt_stage_max: BANKRUPT_STAGE_MAX,
        },
        efficiency: EfficiencyTable {
            max: EFFICIENCY_MAX,
            without_advanced_farming: EFFICIENCY_WITHOUT_ADVANCED_FARMING,
        },
        ale: AleTable { step_pct: ALE_HAPPINESS_STEP_PCT, max: ALE_HAPPINESS_MAX },
        army_happiness_cost: ARMY_HAPPINESS_COST,
        unit: UnitTable {
            move_allowance_army: MOVE_ALLOWANCE_ARMY,
            move_allowance_other: MOVE_ALLOWANCE_OTHER,
            step_cost_road: STEP_COST_ROAD,
            step_cost_open: STEP_COST_OPEN,
            step_cost_field_extra: STEP_COST_FIELD_EXTRA,
            step_cost_trample: STEP_COST_TRAMPLE,
            move_cost_blocked: MOVE_COST_BLOCKED,
            trample_disabled_seasons: TRAMPLE_DISABLED_SEASONS,
            army_max_men: ARMY_MAX_MEN,
            army_min_men: ARMY_MIN_MEN,
            mob_destroyed_below_men: MOB_DESTROYED_BELOW_MEN,
            desertion_pct: DESERTION_PCT,
            desertion_min_troops: DESERTION_MIN_TROOPS,
            starvation_limit: STARVATION_LIMIT,
            levy_surcharge: LEVY_SURCHARGE,
            levy_cost_max: LEVY_COST_MAX,
            levy_auto_equip_batch: LEVY_AUTO_EQUIP_BATCH,
            levy_auto_equip_rounds: LEVY_AUTO_EQUIP_ROUNDS,
            size_class_max: ARMY_SIZE_CLASS_MAX,
        },
        ai: AiTable {
            gold_grant: AI_GOLD_GRANT,
            grant_population_per_difficulty: AI_GRANT_POPULATION_PER_DIFFICULTY,
            grant_herd_per_difficulty: AI_GRANT_HERD_PER_DIFFICULTY,
            grant_grain_per_difficulty: AI_GRANT_GRAIN_PER_DIFFICULTY,
            grant_min_population: AI_GRANT_MIN_POPULATION,
            grant_min_herd: AI_GRANT_MIN_HERD,
            grant_min_grain: AI_GRANT_MIN_GRAIN,
            tax_ladder_neutral: AI_TAX_LADDER_NEUTRAL,
            tax_ladders: AI_TAX_LADDERS,
            personality: [
                AiPersonalityRow {
                    farm_style: AI_PERSONALITY_FARM_STYLE[0],
                    tax_ladder: AI_PERSONALITY_TAX_LADDER[0],
                    gift_increment: AI_PERSONALITY_GIFT_INCREMENT[0],
                    help_price: AI_PERSONALITY_HELP_PRICE[0],
                    grudge_tolerance: AI_PERSONALITY_GRUDGE_TOLERANCE[0],
                    offer_interval: AI_PERSONALITY_OFFER_INTERVAL[0],
                    help_population_floor: AI_PERSONALITY_HELP_POPULATION_FLOOR[0],
                    muster_pct: AI_PERSONALITY_MUSTER_PCT[0],
                    muster_patience: AI_PERSONALITY_MUSTER_PATIENCE[0],
                    muster_arms: AI_PERSONALITY_MUSTER_ARMS[0],
                    garrison_min_population: AI_PERSONALITY_GARRISON_MIN_POPULATION[0],
                    raid_interval: AI_PERSONALITY_RAID_INTERVAL[0],
                    abandon_tax_rate: AI_PERSONALITY_ABANDON_TAX_RATE[0],
                    weapon_rota: AI_PERSONALITY_WEAPON_ROTA[0],
                    castle_concurrent: AI_PERSONALITY_CASTLE_CONCURRENT[0],
                    castle_min_population: AI_PERSONALITY_CASTLE_MIN_POPULATION[0],
                    castle_gold: AI_PERSONALITY_CASTLE_GOLD[0],
                    siege_doctrine: AI_PERSONALITY_SIEGE_DOCTRINE[0],
                    trade_gold_floor: AI_PERSONALITY_TRADE_GOLD_FLOOR[0],
                    weapon_buy_qty: AI_PERSONALITY_WEAPON_BUY_QTY[0],
                    reserve_wood: AI_PERSONALITY_RESERVE_WOOD[0],
                    reserve_stone: AI_PERSONALITY_RESERVE_STONE[0],
                    reserve_iron: AI_PERSONALITY_RESERVE_IRON[0],
                },
                AiPersonalityRow {
                    farm_style: AI_PERSONALITY_FARM_STYLE[1],
                    tax_ladder: AI_PERSONALITY_TAX_LADDER[1],
                    gift_increment: AI_PERSONALITY_GIFT_INCREMENT[1],
                    help_price: AI_PERSONALITY_HELP_PRICE[1],
                    grudge_tolerance: AI_PERSONALITY_GRUDGE_TOLERANCE[1],
                    offer_interval: AI_PERSONALITY_OFFER_INTERVAL[1],
                    help_population_floor: AI_PERSONALITY_HELP_POPULATION_FLOOR[1],
                    muster_pct: AI_PERSONALITY_MUSTER_PCT[1],
                    muster_patience: AI_PERSONALITY_MUSTER_PATIENCE[1],
                    muster_arms: AI_PERSONALITY_MUSTER_ARMS[1],
                    garrison_min_population: AI_PERSONALITY_GARRISON_MIN_POPULATION[1],
                    raid_interval: AI_PERSONALITY_RAID_INTERVAL[1],
                    abandon_tax_rate: AI_PERSONALITY_ABANDON_TAX_RATE[1],
                    weapon_rota: AI_PERSONALITY_WEAPON_ROTA[1],
                    castle_concurrent: AI_PERSONALITY_CASTLE_CONCURRENT[1],
                    castle_min_population: AI_PERSONALITY_CASTLE_MIN_POPULATION[1],
                    castle_gold: AI_PERSONALITY_CASTLE_GOLD[1],
                    siege_doctrine: AI_PERSONALITY_SIEGE_DOCTRINE[1],
                    trade_gold_floor: AI_PERSONALITY_TRADE_GOLD_FLOOR[1],
                    weapon_buy_qty: AI_PERSONALITY_WEAPON_BUY_QTY[1],
                    reserve_wood: AI_PERSONALITY_RESERVE_WOOD[1],
                    reserve_stone: AI_PERSONALITY_RESERVE_STONE[1],
                    reserve_iron: AI_PERSONALITY_RESERVE_IRON[1],
                },
                AiPersonalityRow {
                    farm_style: AI_PERSONALITY_FARM_STYLE[2],
                    tax_ladder: AI_PERSONALITY_TAX_LADDER[2],
                    gift_increment: AI_PERSONALITY_GIFT_INCREMENT[2],
                    help_price: AI_PERSONALITY_HELP_PRICE[2],
                    grudge_tolerance: AI_PERSONALITY_GRUDGE_TOLERANCE[2],
                    offer_interval: AI_PERSONALITY_OFFER_INTERVAL[2],
                    help_population_floor: AI_PERSONALITY_HELP_POPULATION_FLOOR[2],
                    muster_pct: AI_PERSONALITY_MUSTER_PCT[2],
                    muster_patience: AI_PERSONALITY_MUSTER_PATIENCE[2],
                    muster_arms: AI_PERSONALITY_MUSTER_ARMS[2],
                    garrison_min_population: AI_PERSONALITY_GARRISON_MIN_POPULATION[2],
                    raid_interval: AI_PERSONALITY_RAID_INTERVAL[2],
                    abandon_tax_rate: AI_PERSONALITY_ABANDON_TAX_RATE[2],
                    weapon_rota: AI_PERSONALITY_WEAPON_ROTA[2],
                    castle_concurrent: AI_PERSONALITY_CASTLE_CONCURRENT[2],
                    castle_min_population: AI_PERSONALITY_CASTLE_MIN_POPULATION[2],
                    castle_gold: AI_PERSONALITY_CASTLE_GOLD[2],
                    siege_doctrine: AI_PERSONALITY_SIEGE_DOCTRINE[2],
                    trade_gold_floor: AI_PERSONALITY_TRADE_GOLD_FLOOR[2],
                    weapon_buy_qty: AI_PERSONALITY_WEAPON_BUY_QTY[2],
                    reserve_wood: AI_PERSONALITY_RESERVE_WOOD[2],
                    reserve_stone: AI_PERSONALITY_RESERVE_STONE[2],
                    reserve_iron: AI_PERSONALITY_RESERVE_IRON[2],
                },
                AiPersonalityRow {
                    farm_style: AI_PERSONALITY_FARM_STYLE[3],
                    tax_ladder: AI_PERSONALITY_TAX_LADDER[3],
                    gift_increment: AI_PERSONALITY_GIFT_INCREMENT[3],
                    help_price: AI_PERSONALITY_HELP_PRICE[3],
                    grudge_tolerance: AI_PERSONALITY_GRUDGE_TOLERANCE[3],
                    offer_interval: AI_PERSONALITY_OFFER_INTERVAL[3],
                    help_population_floor: AI_PERSONALITY_HELP_POPULATION_FLOOR[3],
                    muster_pct: AI_PERSONALITY_MUSTER_PCT[3],
                    muster_patience: AI_PERSONALITY_MUSTER_PATIENCE[3],
                    muster_arms: AI_PERSONALITY_MUSTER_ARMS[3],
                    garrison_min_population: AI_PERSONALITY_GARRISON_MIN_POPULATION[3],
                    raid_interval: AI_PERSONALITY_RAID_INTERVAL[3],
                    abandon_tax_rate: AI_PERSONALITY_ABANDON_TAX_RATE[3],
                    weapon_rota: AI_PERSONALITY_WEAPON_ROTA[3],
                    castle_concurrent: AI_PERSONALITY_CASTLE_CONCURRENT[3],
                    castle_min_population: AI_PERSONALITY_CASTLE_MIN_POPULATION[3],
                    castle_gold: AI_PERSONALITY_CASTLE_GOLD[3],
                    siege_doctrine: AI_PERSONALITY_SIEGE_DOCTRINE[3],
                    trade_gold_floor: AI_PERSONALITY_TRADE_GOLD_FLOOR[3],
                    weapon_buy_qty: AI_PERSONALITY_WEAPON_BUY_QTY[3],
                    reserve_wood: AI_PERSONALITY_RESERVE_WOOD[3],
                    reserve_stone: AI_PERSONALITY_RESERVE_STONE[3],
                    reserve_iron: AI_PERSONALITY_RESERVE_IRON[3],
                },
            ],
        },
        score: ScoreTable {
            gold_brackets: [(10_001, 50), (5_001, 50), (2_001, 50), (0, 0)],
            weights: SCORE_WEIGHTS,
            input_offsets: SCORE_INPUT_OFFSETS,
        },
    };

}

