// Decompile every function in the program to one searchable tree of C.
//
// Why this exists
// ---------------
// Until now every question was answered by starting Ghidra, decompiling a
// handful of functions, and writing the result into a per-task out/ directory.
// Six of those accumulated - roughly 6.4 MB of overlapping, fragmentary C - and
// every new question paid the analysis cost again. Producing the C is the cheap
// part; Ghidra will do the whole binary in one run. Understanding it is what is
// expensive, and that is not helped by re-deriving it.
//
// So: decompile everything once, into files that can be grepped. Questions like
// "who else writes this global?" or "where else does this constant appear?"
// become a text search over the whole program rather than a new headless run
// and a guess about where to look.
//
// Run it again after docs/symbols.json changes, so names propagate: naming
// g_pathCost once makes fifty unrelated functions legible, and this is how that
// benefit reaches code nobody has looked at yet.
//
// Output layout, one file per 0x10000 of address space so no file is enormous
// and the address tells you which file to open:
//
//     <outdir>/0047xxxx.c
//     <outdir>/index.txt     address, name, size, param count - one line each
//
// Usage:
//   analyzeHeadless <proj> <name> -process Lords2.exe -noanalysis \
//       -scriptPath ghidra_scripts -postScript DecompileAll <outdir>
//
//@category Lords2

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;

import java.io.File;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;

public class DecompileAll extends GhidraScript {

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            println("usage: DecompileAll <outdir>");
            return;
        }
        File outDir = new File(args[0]);
        if (!outDir.isAbsolute()) {
            outDir = new File(getSourceFile().getParentFile().getParentFile().getFile(false), args[0]);
        }
        outDir.mkdirs();

        DecompInterface di = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        di.setOptions(opts);
        di.openProgram(currentProgram);

        // One writer per 64 KB bucket, so a function's address tells you which
        // file it is in without consulting the index.
        Map<String, PrintWriter> writers = new HashMap<>();
        PrintWriter index = new PrintWriter(new File(outDir, "index.txt"), "UTF-8");
        index.println("# address  name  bytes  params  bucket");

        int done = 0, failed = 0;
        try {
            FunctionIterator it = currentProgram.getFunctionManager().getFunctions(true);
            while (it.hasNext()) {
                if (monitor.isCancelled()) {
                    break;
                }
                Function f = it.next();
                long entry = f.getEntryPoint().getOffset();
                String bucket = String.format("%04x0000", entry >>> 16);

                index.printf("%08x  %-44s %7d %3d  %s%n",
                        entry, f.getName(), f.getBody().getNumAddresses(),
                        f.getParameterCount(), bucket);

                PrintWriter w = writers.get(bucket);
                if (w == null) {
                    w = new PrintWriter(new File(outDir, bucket + ".c"), "UTF-8");
                    w.println("// Decompiled functions in " + bucket + "..+0xffff");
                    w.println("// Generated by ghidra_scripts/DecompileAll.java - do not edit.");
                    w.println("// Derived from the shipped binary: gitignored, never committed.");
                    writers.put(bucket, w);
                }

                // 60s each. A handful of enormous functions time out; they are
                // recorded rather than silently missing, because a gap you
                // cannot see is worse than one you can.
                DecompileResults res = di.decompileFunction(f, 60, monitor);
                w.println();
                w.printf("// ==== %08x  %s  params=%d  bytes=%d%n",
                        entry, f.getName(), f.getParameterCount(),
                        f.getBody().getNumAddresses());
                if (res != null && res.decompileCompleted()) {
                    w.println(res.getDecompiledFunction().getC());
                    done++;
                } else {
                    String why = res == null ? "no result" : res.getErrorMessage();
                    w.println("// DECOMPILE FAILED: " + why);
                    failed++;
                }

                if ((done + failed) % 200 == 0) {
                    println("decompiled " + (done + failed) + " functions...");
                }
            }
        } finally {
            for (PrintWriter w : writers.values()) {
                w.close();
            }
            index.close();
            di.dispose();
        }

        println("DecompileAll: " + done + " decompiled, " + failed + " failed, "
                + writers.size() + " files in " + outDir.getAbsolutePath());
    }
}
